sourcepath: student.csv
source-output: src/main/resources/csv/student.csv

spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: true
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
